# Generated by Django 5.1 on 2025-03-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_options_alter_user_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Chef', 'Chef'), ('User', 'User')], default='User', max_length=10),
        ),
    ]
