# Generated by Django 5.1 on 2025-03-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_verification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
