# Generated by Django 5.1 on 2025-03-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
