# Generated by Django 5.1 on 2025-03-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_reaction_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
