# Generated by Django 5.1.1 on 2025-03-19 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_remove_contactus_phone_contactus_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 19, 7, 25, 0, 851437, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
